export const Fake_Object = [
  {
    backdrop_path: "/m0bV3qBiJBBlpFaaKjwHo13MVjm.jpg",
    first_air_date: "2005-01-03",
    genre_ids: [35, 10767],
    id: 14981,
    name: "The Late Late Show with Craig Ferguson",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Late Late Show with Craig Ferguson",
    overview:
      "The Late Late Show with Craig Ferguson is an American late-night talk show hosted by Scottish American comedian Craig Ferguson, who is the third regular host of the Late Late Show franchise. It follows Late Show with David Letterman in the CBS late-night lineup, airing weekdays in the US at 12:37 a.m. It is taped in front of a live studio audience from Monday to Friday at CBS Television City in Los Angeles, California, directly above the Bob Barker Studio. It is produced by David Letterman's production company Worldwide Pants Incorporated and CBS Television Studios.\n\nSince becoming host on January 3, 2005, after Craig Kilborn and Tom Snyder, Ferguson has achieved the highest ratings since the show's inception in 1995. While the majority of the episodes focus on comedy, Ferguson has also addressed difficult subject matter, such as the deaths of his parents, and undertaken serious interviews, such as one with Desmond Tutu, which earned the show a 2009 Peabody Award.",
    popularity: 11809.245,
    poster_path: "/gGC7zSDgG0FY0MbM1pjfhTCWQBI.jpg",
    vote_average: 8.1,
    vote_count: 76,
  },
];
export const Fake_Recommendation = [
  {
    adult: false,
    backdrop_path: "/9In9QgVJx7PlFOAgVHCKKSbo605.jpg",
    id: 60625,
    name: "Rick and Morty",
    original_language: "en",
    original_name: "Rick and Morty",
    overview:
      "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
    poster_path: "/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 10765, 10759],
    popularity: 701.077,
    first_air_date: "2013-12-02",
    vote_average: 8.701,
    vote_count: 8554,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/pMCvRynXABgLBMKHYa2UXjTBMsU.jpg",
    id: 615,
    name: "Futurama",
    original_language: "en",
    original_name: "Futurama",
    overview:
      "The adventures of a late-20th-century New York City pizza delivery boy, Philip J. Fry, who, after being unwittingly cryogenically frozen for one thousand years, finds employment at Planet Express, an interplanetary delivery company in the retro-futuristic 31st century.",
    poster_path: "/7RRHbCUtAsVmKI6FEMzZB6Re88P.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 10765],
    popularity: 609.071,
    first_air_date: "1999-03-28",
    vote_average: 8.396,
    vote_count: 2853,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/j5w04XEuFv85N3RIovXBJIHxjSb.jpg",
    id: 1920,
    name: "Twin Peaks",
    original_language: "en",
    original_name: "Twin Peaks",
    overview:
      "The body of Laura Palmer is washed up on a beach near the small Washington state town of Twin Peaks. FBI Special Agent Dale Cooper is called in to investigate her strange demise only to uncover a web of mystery that ultimately leads him deep into the heart of the surrounding woodland and his very own soul.",
    poster_path: "/lA9CNSdo50iQPZ8A2fyVpMvJZAf.jpg",
    media_type: "tv",
    genre_ids: [18, 9648],
    popularity: 105.044,
    first_air_date: "1990-04-08",
    vote_average: 8.3,
    vote_count: 1762,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/a906PH7CDmSOdS7kmnAgdWk5mhv.jpg",
    id: 67744,
    name: "Mindhunter",
    original_language: "en",
    original_name: "Mindhunter",
    overview:
      "An agent in the FBI's Elite Serial Crime Unit develops profiling techniques as he pursues notorious serial killers and rapists.",
    poster_path: "/fbKE87mojpIETWepSbD5Qt741fp.jpg",
    media_type: "tv",
    genre_ids: [18, 80],
    popularity: 50.568,
    first_air_date: "2017-10-13",
    vote_average: 8.069,
    vote_count: 2077,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/zP5SftyPx2VCdly369kTVVNIcT3.jpg",
    id: 1404,
    name: "Chuck",
    original_language: "en",
    original_name: "Chuck",
    overview:
      "When Buy More computer geek Chuck Bartowski unwittingly downloads a database of government information and deadly fighting skills into his head, he becomes the CIA's most vital secret. This sets Chuck on a path to become a full-fledged spy.",
    poster_path: "/vEZvGVVMjk1TRs59nfypTI5lAXj.jpg",
    media_type: "tv",
    genre_ids: [10759, 35, 18],
    popularity: 129.942,
    first_air_date: "2007-09-24",
    vote_average: 7.74,
    vote_count: 874,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/8PtOfFfX3anE4T63NjnfULRalMq.jpg",
    id: 186,
    name: "Weeds",
    original_language: "en",
    original_name: "Weeds",
    overview:
      "After the unexpected death of her husband, a suburban mom resorts to selling weed to support her family.",
    poster_path: "/gKUsBTa5b0GY7U4iWBseeBalfjO.jpg",
    media_type: "tv",
    genre_ids: [35, 80, 18],
    popularity: 61.416,
    first_air_date: "2005-08-07",
    vote_average: 7.461,
    vote_count: 744,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/mlAzs3tyl5253roHi6eIRbeuONN.jpg",
    id: 1400,
    name: "Seinfeld",
    original_language: "en",
    original_name: "Seinfeld",
    overview:
      "A stand-up comedian and his three offbeat friends weather the pitfalls and payoffs of life in New York City in the '90s. It's a show about nothing.",
    poster_path: "/aCw8ONfyz3AhngVQa1E2Ss4KSUQ.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 454.56,
    first_air_date: "1989-07-05",
    vote_average: 8.283,
    vote_count: 1650,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/qCXY93t7QnKp6aWT1WKaQo0Qt5r.jpg",
    id: 4589,
    name: "Arrested Development",
    original_language: "en",
    original_name: "Arrested Development",
    overview:
      "The story of a wealthy family that lost everything, and the one son who had no choice but to keep them all together.",
    poster_path: "/qMzwO952hMWQSCfHkp7IL20s4K7.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 101.785,
    first_air_date: "2003-11-02",
    vote_average: 7.978,
    vote_count: 1166,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/rFdBQdtOoeIVzmXbzSZEo0GIqoE.jpg",
    id: 96580,
    name: "Resident Alien",
    original_language: "en",
    original_name: "Resident Alien",
    overview:
      "Crash-landed alien Harry takes on the identity of a small-town Colorado doctor. Arriving with a secret mission, he starts off living a simple life…but things get a bit rocky when he’s roped into solving a local murder and realizes he needs to assimilate into his new world. As he does, he begins to wrestle with the moral dilemma of his mission and asking the big life questions like: “Are human beings worth saving?” and “Why do they fold their pizza before eating it?”",
    poster_path: "/uJMbW9d1QqoJWmGOqJv8mAbegac.jpg",
    media_type: "tv",
    genre_ids: [10765],
    popularity: 75.708,
    first_air_date: "2021-01-27",
    vote_average: 7.986,
    vote_count: 561,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/pXpK8GnLL0wZkfelg5lCVSOnytN.jpg",
    id: 1950,
    name: "Everwood",
    original_language: "en",
    original_name: "Everwood",
    overview:
      "After the death of his wife, world-class neurosurgeon Dr. Andrew Brown leaves Manhattan and moves his family to the small town of Everwood, Colorado. There he becomes a small-town doctor and learns parenting on the fly as he raises his talented but resentful 15-year-old son Ephram and his 9-year-old daughter Delia.",
    poster_path: "/4zmuA2Ql1QdUtw9OM6MdmtXnZEF.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 143.126,
    first_air_date: "2002-09-16",
    vote_average: 7.629,
    vote_count: 163,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/f1Z5X3iCCKK5FGu5VvzPkXO7eOl.jpg",
    id: 64199,
    name: "Sneaky Pete",
    original_language: "en",
    original_name: "Sneaky Pete",
    overview:
      "A con man on the run from a vicious gangster takes cover from his past by assuming the identity of his prison cellmate, Pete, “reuniting” with Pete’s estranged family, a colorful, dysfunctional group that threatens to drag him into a world just as dangerous as the one he’s trying to escape - and, just maybe, give him a taste of the loving family he’s never had.",
    poster_path: "/5dU7taWEgoH1RnmBqyUKmcD4ig4.jpg",
    media_type: "tv",
    genre_ids: [18, 80],
    popularity: 48.575,
    first_air_date: "2015-08-07",
    vote_average: 7.598,
    vote_count: 266,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/tKnMnMU6U8TXxjvCVm6LEA0xnE4.jpg",
    id: 790,
    name: "Agatha Christie's Poirot",
    original_language: "en",
    original_name: "Agatha Christie's Poirot",
    overview:
      "From England to Egypt, accompanied by his elegant and trustworthy sidekicks, the intelligent yet eccentrically-refined Belgian detective Hercule Poirot pits his wits against a collection of first class deceptions.",
    poster_path: "/KX69tBuobsjtr9ea1J5OxtvIV1.jpg",
    media_type: "tv",
    genre_ids: [80, 18, 9648],
    popularity: 240.908,
    first_air_date: "1989-01-08",
    vote_average: 8.171,
    vote_count: 387,
    origin_country: ["GB"],
  },
  {
    adult: false,
    backdrop_path: "/uHiQS8rMaXSj5Jb9Rd7nUTDMVMw.jpg",
    id: 2009,
    name: "Rocket Power",
    original_language: "en",
    original_name: "Rocket Power",
    overview:
      "The daily lives of four friends who enjoy extreme sports, surfing, and getting into some crazy situations.",
    poster_path: "/gWPYp1PjYpxgNNMpsFEBC8deOX.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 10751],
    popularity: 56.163,
    first_air_date: "1999-08-16",
    vote_average: 7.787,
    vote_count: 279,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/7w4OCRKq00tMAJlwVwW8vyFSodx.jpg",
    id: 2552,
    name: "Mork & Mindy",
    original_language: "en",
    original_name: "Mork & Mindy",
    overview:
      "An American science fiction sitcom broadcast from 1978 until 1982 on ABC, starring Robin Williams as Mork, an alien who comes to Earth from the planet Ork in a small, one-man egg-shaped spaceship and Pam Dawber as Mindy McConnell, his human friend and roommate. In 1997, the episode 'Mork's Mixed Emotions' was ranked #94 on TV Guide's 100 Greatest Episodes of All Time list.",
    poster_path: "/mzWJikslTFFeRloUNQmbAWbdU28.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 88.306,
    first_air_date: "1978-09-14",
    vote_average: 7.004,
    vote_count: 119,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/bYx97fcrrAQOJldXdKW4iXCsHsl.jpg",
    id: 56590,
    name: "The Eric Andre Show",
    original_language: "en",
    original_name: "The Eric Andre Show",
    overview:
      "A comedic talk show from an alternate reality featuring unstable hosts, a variety of celebrities—both real and fake—and unusual studio action.",
    poster_path: "/3OX22kBMeDBxgYNlVuMYlieoanM.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 108.794,
    first_air_date: "2012-05-20",
    vote_average: 7.964,
    vote_count: 110,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/uSNmMsfadV5dEhYEwqn6Kojctj9.jpg",
    id: 1706,
    name: "The Pretender",
    original_language: "en",
    original_name: "The Pretender",
    overview:
      "Raised in a secret facility built for experimenting on children, Jarod is a genius who can master any profession and become anyone he has to be. When he realizes as an adult that he's actually a prisoner and his captors are not as benevolent as he's been told, he breaks out. While trying to find his real identity, Jarod helps those he encounters and tries to avoid the woman sent to retrieve him.",
    poster_path: "/76q5tPOPQkQYIuZu2SG6viZcp2b.jpg",
    media_type: "tv",
    genre_ids: [18, 9648, 10765],
    popularity: 103.229,
    first_air_date: "1996-09-19",
    vote_average: 7.339,
    vote_count: 165,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/wULya1x9ohox6rHar574a13ml4O.jpg",
    id: 72235,
    name: "The Voice Kids",
    original_language: "en",
    original_name: "The Voice Kids",
    overview:
      "Talented young solo singers between the ages of 7 and 14 wow coaches and audiences alike in a bid to become the next big thing!",
    poster_path: "/13RWdJBpVb0pdM7bzuhg6vfhXRY.jpg",
    media_type: "tv",
    genre_ids: [10764, 10762, 10751],
    popularity: 20.902,
    first_air_date: "2017-06-10",
    vote_average: 5.9,
    vote_count: 10,
    origin_country: ["GB"],
  },
  {
    adult: false,
    backdrop_path: "/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg",
    id: 71446,
    name: "Money Heist",
    original_language: "es",
    original_name: "La Casa de Papel",
    overview:
      "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
    poster_path: "/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 99.631,
    first_air_date: "2017-05-02",
    vote_average: 8.258,
    vote_count: 17796,
    origin_country: ["ES"],
  },
  {
    adult: false,
    backdrop_path: "/y5NFQD2yTGoPLy1KdlBcAwuecqW.jpg",
    id: 19885,
    name: "Sherlock",
    original_language: "en",
    original_name: "Sherlock",
    overview:
      "A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.",
    poster_path: "/7WTsnHkbA0FaG6R9twfFde0I9hl.jpg",
    media_type: "tv",
    genre_ids: [80, 18, 9648],
    popularity: 85.564,
    first_air_date: "2010-07-25",
    vote_average: 8.538,
    vote_count: 4685,
    origin_country: ["GB"],
  },
  {
    adult: false,
    backdrop_path: "/2MaumbgBlW1NoPo3ZJO38A6v7OS.jpg",
    id: 66732,
    name: "Stranger Things",
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 9648],
    popularity: 353.064,
    first_air_date: "2016-07-15",
    vote_average: 8.626,
    vote_count: 16081,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/lHe8iwM4Cdm6RSEiara4PN8ZcBd.jpg",
    id: 44217,
    name: "Vikings",
    original_language: "en",
    original_name: "Vikings",
    overview:
      "The adventures of Ragnar Lothbrok, the greatest hero of his age. The series tells the sagas of Ragnar's band of Viking brothers and his family, as he rises to become King of the Viking tribes. As well as being a fearless warrior, Ragnar embodies the Norse traditions of devotion to the gods. Legend has it that he was a direct descendant of Odin, the god of war and warriors.",
    poster_path: "/bQLrHIRNEkE3PdIWQrZHynQZazu.jpg",
    media_type: "tv",
    genre_ids: [10759, 18, 10768],
    popularity: 394.448,
    first_air_date: "2013-03-03",
    vote_average: 8.084,
    vote_count: 6358,
    origin_country: ["CA"],
  },
];
